version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: petwatch
      POSTGRES_PASSWORD: petwatch123
      POSTGRES_DB: petwatch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petwatch -d petwatch_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: